version: '3'

services:
  scylladb:
    image: scylladb/scylla
    container_name: scylladb
    ports:
      - 9042:9042

 # zookeeper:
 #   image: wurstmeister/zookeeper
 #   ports:
 #     - 2181:2181
 #   container_name: zookeeper

 # kafka:
 #   image: wurstmeister/kafka
 #   container_name: kafka
 #   depends_on:
 #     - zookeeper
 #   ports:
 #     - 9092:9092
 #   environment:
 #     KAFKA_ADVERTISED_HOST_NAME: localhost
 #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
 #     KAFKA_CREATE_TOPICS: "BR.CDF.UBO.receive.records:1:1,BR.CDF.UBO.send.records:1:1"
